Repository roboflow/inference, pull requests merged in 2023-10, with the labels that each got.

#69 Update inference video on docs
  docs/index.md
Labels: documentation

#55 Add CLIP and SAM examples, add new docs
  README.md
  docs/add_a_model.md
  docs/changelog.md
  docs/contributing.md
  examples/README.md
  examples/clip-search-engine/README.md
  examples/clip-search-engine/app.py
  examples/clip-search-engine/requirements.txt
  examples/clip-search-engine/templates/index.html
  examples/sam-client/README.md
  examples/sam-client/app.py
  examples/sam-client/requirements.txt
  mkdocs.yml
Labels: documentation

#102 Add 404 page
  custom_theme/404.html
  mkdocs.yml
Labels: documentation

#54 Add DocTR to Inference
  docker/dockerfiles/Dockerfile.onnx.cpu
  docker/dockerfiles/Dockerfile.onnx.gpu
  docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
  docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
  docker/dockerfiles/Dockerfile.onnx.lambda
  docker/dockerfiles/Dockerfile.onnx.trt
  docs/index.md
  docs/library/models/doctr.md
  inference/core/entities/requests/doctr.py
  inference/core/entities/responses/doctr.py
  inference/core/env.py
  inference/core/interfaces/http/http_api.py
  inference/core/registries/roboflow.py
  inference/core/utils/image_utils.py
  inference/models/__init__.py
  inference/models/doctr/LICENSE.txt
  inference/models/doctr/__init__.py
  inference/models/doctr/doctr_model.py
  inference/models/utils.py
  requirements/requirements.doctr.txt
  requirements/requirements.groundingdino.txt
  tests/inference/integration_tests/doctr_test.py
Labels: new model

#123 Add compatability matrix template
  docs/quickstart/compatability_matrix.md
  mkdocs.yml
Labels: documentation

#129 Update compatability_matrix.md
  docs/quickstart/compatability_matrix.md
Labels: documentation

#142 Update default API key parameter for get_roboflow_model function
  inference/models/utils.py
Labels: bug

#133 Documentation improvements
  docs/add_a_model.md
  docs/contributing.md
  docs/foundation/about.md
  docs/foundation/clip.md
  docs/foundation/doctr.md
  docs/foundation/gaze.md
  docs/foundation/grounding_dino.md
  docs/foundation/sam.md
  docs/index.md
  docs/library/data_models/clip/clip_compare_request.md
  docs/library/data_models/clip/clip_image_embedding_request.md
  docs/library/data_models/clip/clip_inference_request.md
  docs/library/data_models/clip/clip_text_embedding_request.md
  docs/library/data_models/inference/classification.md
  docs/library/data_models/inference/cv_inference_request.md
  docs/library/data_models/inference/inference_request_image.md
  docs/library/data_models/inference/instance_segmentation.md
  docs/library/data_models/inference/object_detection.md
  docs/library/data_models/sam/sam_embedding_request.md
  docs/library/data_models/sam/sam_segmentation_request.md
  docs/library/interfaces/base.md
  docs/library/interfaces/http.md
  docs/library/interfaces/udp.md
  docs/library/model_managers/base.md
  docs/library/model_managers/pingback.md
  docs/library/model_registries/base.md
  docs/library/model_registries/roboflow.md
  docs/library/models/clip.md
  docs/library/models/doctr.md
  docs/library/models/gaze.md
  docs/library/models/segment_anything.md
  docs/library/models/vit_classification.md
  docs/library/models/yoloact_segmentation.md
  docs/library/models/yolov5.md
  docs/library/models/yolov5_segmentation.md
  docs/library/models/yolov7_instance_segmentation.md
  docs/library/models/yolov8.md
  docs/library/models/yolov8_classification.md
  docs/library/models/yolov8_segmentation.md
  docs/quickstart/devices.md
  docs/quickstart/docker.md
  docs/quickstart/docker_configuration_options.md
  docs/quickstart/explore_models.md
  docs/quickstart/getting_started.md
  docs/quickstart/library_inference.md
  docs/quickstart/licensing.md
  docs/quickstart/run_a_model.md
  docs/quickstart/run_model_on_image.md
  docs/quickstart/run_model_on_rtsp_webcam.md
  docs/quickstart/run_model_over_udp.md
  docs/quickstart/what_is_inference.md
  docs/styles.css
  mkdocs.yml
Labels: documentation
