Repository roboflow/inference, pull requests merged in 2024-08, with the labels that each got.

#502 Add Inference Windows CUDA documentation
  docs/quickstart/inference_gpu_windows.md
  mkdocs.yml
Labels: documentation

#593 Sam2 multi polygons
  inference/core/entities/responses/sam2.py
  inference/core/utils/postprocess.py
  inference/core/workflows/core_steps/models/foundation/segment_anything2/v1.py
  inference/models/sam2/segment_anything2.py
  tests/inference/models_predictions_tests/assets/sam2_multipolygon_response.json
  tests/inference/models_predictions_tests/conftest.py
  tests/inference/models_predictions_tests/test_sam2.py
  tests/workflows/integration_tests/execution/test_workflow_with_sam2.py
Labels: sam2

#620 Adding block to assist in setting camera focus
  inference/core/workflows/core_steps/classical_cv/camera_focus/__init__.py
  inference/core/workflows/core_steps/classical_cv/camera_focus/v1.py
  inference/core/workflows/core_steps/loader.py
  tests/inference/models_predictions_tests/conftest.py
  tests/inference/models_predictions_tests/test_sam2.py
  tests/inference/unit_tests/core/utils/test_sqlite_wrapper.py
  tests/workflows/integration_tests/execution/test_workflow_with_camera_focus.py
  tests/workflows/integration_tests/execution/test_workflow_with_contours_detection.py
  tests/workflows/integration_tests/execution/test_workflow_with_counting_pixels_with_dominant_color.py
  tests/workflows/integration_tests/execution/test_workflow_with_dominant_color.py
  tests/workflows/integration_tests/execution/test_workflow_with_sahi.py
  tests/workflows/integration_tests/execution/test_workflow_with_sam2.py
  tests/workflows/integration_tests/execution/test_workflow_with_sift.py
  tests/workflows/integration_tests/execution/test_workflow_with_stitch_for_dynamic_crop.py
  tests/workflows/unit_tests/core_steps/classical_cv/test_camera_focus.py
  tests/workflows/unit_tests/core_steps/transformations/test_detection_offset.py
Labels: release 0.17.0

#613 Dataset Upload Block- Changed the default for upload max_image_size
  inference/core/version.py
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/sinks/roboflow/dataset_upload/v1.py
  inference/core/workflows/core_steps/sinks/roboflow/dataset_upload/v2.py
  tests/workflows/integration_tests/execution/test_workflow_with_active_learning_sink.py
  tests/workflows/unit_tests/core_steps/sinks/roboflow/roboflow_dataset_upload/__init__.py
  tests/workflows/unit_tests/core_steps/sinks/roboflow/roboflow_dataset_upload/test_v1.py
  tests/workflows/unit_tests/core_steps/sinks/roboflow/roboflow_dataset_upload/test_v2.py
Labels: release 0.17.0, release-branch
