Repository roboflow/inference, pull requests merged in 2024-09, with the labels that each got.

#622 Add e2e tests for `workflows` on hosted platform
  tests/inference/hosted_platform_tests/conftest.py
  tests/inference/hosted_platform_tests/test_workflows.py
  tests/inference/hosted_platform_tests/workflows_examples/__init__.py
  tests/inference/hosted_platform_tests/workflows_examples/conftest.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_clip.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_dataset_upload.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_detection_and_crop.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_openai.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_sahi.py
Labels: tests-enhancement

#623 Docs enhancement
  development/docs/build_block_docs.py
  docs/workflows/blocks.md
  docs/workflows/create_workflow_block.md
  docs/workflows/kinds.md
  inference/core/workflows/core_steps/classical_cv/template_matching/v1.py
  inference/core/workflows/core_steps/flow_control/continue_if/v1.py
  inference/core/workflows/core_steps/formatters/expression/v1.py
  inference/core/workflows/core_steps/formatters/property_definition/v1.py
  inference/core/workflows/core_steps/models/foundation/lmm/v1.py
  inference/core/workflows/core_steps/models/foundation/lmm_classifier/v1.py
  inference/core/workflows/core_steps/models/foundation/openai/v1.py
  inference/core/workflows/core_steps/sinks/roboflow/custom_metadata/v1.py
  inference/core/workflows/core_steps/sinks/roboflow/dataset_upload/v1.py
  inference/core/workflows/core_steps/transformations/detections_filter/v1.py
  inference/core/workflows/core_steps/transformations/detections_transformation/v1.py
  inference/core/workflows/core_steps/transformations/dynamic_zones/v1.py
  inference/core/workflows/core_steps/transformations/perspective_correction/v1.py
  inference/core/workflows/core_steps/visualizations/common/base.py
  inference/core/workflows/execution_engine/introspection/schema_parser.py
  mkdocs.yml
Labels: release 0.18.0, docs-enhancement

#631 Add support for DELETE in sqlite wrapper
  inference/core/utils/sqlite_wrapper.py
  inference/usage_tracking/sqlite_queue.py
  tests/inference/unit_tests/core/utils/test_sqlite_wrapper.py
  tests/inference/unit_tests/usage_tracking/test_persistent_queue.py
Labels: release 0.18.0

#632 Keep distinct exec sessions for inf pipeline usage
  inference/usage_tracking/collector.py
  inference/usage_tracking/payload_helpers.py
  inference/usage_tracking/redis_queue.py
  inference/usage_tracking/utils.py
  tests/inference/unit_tests/usage_tracking/test_collector.py
Labels: release 0.18.0

#633 Insert usage payloads into redis and to sorted set atomically
  inference/usage_tracking/redis_queue.py
Labels: release 0.18.0

#637 Fix problem with VLM as classifier block
  inference/core/version.py
  inference/core/workflows/core_steps/formatters/vlm_as_classifier/v1.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_claude.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_gemini.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_openai.py
  tests/workflows/integration_tests/execution/test_workflow_with_claude_models.py
  tests/workflows/integration_tests/execution/test_workflow_with_gemini_models.py
  tests/workflows/integration_tests/execution/test_workflow_with_open_ai_models.py
  tests/workflows/unit_tests/core_steps/formatters/test_vlm_as_classifier.py
Labels: release-branch, release 0.18.1

#643 Owlv2
  docker/dockerfiles/Dockerfile.onnx.cpu
  docker/dockerfiles/Dockerfile.onnx.gpu
  docs/foundation/owlv2.md
  inference/core/entities/requests/owlv2.py
  inference/core/env.py
  inference/core/interfaces/http/http_api.py
  inference/core/registries/roboflow.py
  inference/models/owlv2/__init__.py
  inference/models/owlv2/owlv2.py
  inference/models/utils.py
  mkdocs.yml
  tests/inference/models_predictions_tests/test_owlv2.py
Labels: release 0.19.0

#636 Cache plan details
  inference/core/utils/sqlite_wrapper.py
  inference/usage_tracking/collector.py
  inference/usage_tracking/config.py
  inference/usage_tracking/plan_details.py
  inference/usage_tracking/sqlite_queue.py
  tests/inference/unit_tests/core/utils/test_sqlite_wrapper.py
  tests/inference/unit_tests/usage_tracking/test_plan_details.py
Labels: release 0.19.0

#645 Fix problem with lineage and conditional execution
  inference/core/workflows/execution_engine/v1/core.py
  inference/core/workflows/execution_engine/v1/executor/core.py
  tests/inference/hosted_platform_tests/test_workflows.py
  tests/inference/integration_tests/test_workflow_endpoints.py
  tests/inference/models_predictions_tests/test_florence2.py
  tests/workflows/integration_tests/execution/test_workflow_with_branching_affecting_lineage.py
Labels: release 0.19.0

#642 Add Byte Tracker block, Line Counter block and Time In Zone block
  .github/workflows/integration_tests_inference_models.yml
  .github/workflows/integration_tests_workflows_x86.yml
  .github/workflows/test_package_install_inference_gpu_with_extras.yml
  .github/workflows/test_package_install_inference_with_extras.yml
  development/stream_interface/time_in_zone_demo.py
  inference/core/workflows/core_steps/analytics/__init__.py
  inference/core/workflows/core_steps/analytics/line_counter/__init__.py
  inference/core/workflows/core_steps/analytics/line_counter/v1.py
  inference/core/workflows/core_steps/analytics/time_in_zone/__init__.py
  inference/core/workflows/core_steps/analytics/time_in_zone/v1.py
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/transformations/byte_tracker/__init__.py
  inference/core/workflows/core_steps/transformations/byte_tracker/v1.py
  inference/core/workflows/core_steps/visualizations/label/v1.py
  requirements/_requirements.txt
  tests/inference/unit_tests/core/utils/test_sqlite_wrapper.py
  tests/inference/unit_tests/usage_tracking/test_plan_details.py
  tests/workflows/unit_tests/core_steps/analytics/__init__.py
  tests/workflows/unit_tests/core_steps/analytics/test_line_counter.py
  tests/workflows/unit_tests/core_steps/analytics/test_time_in_zone.py
  tests/workflows/unit_tests/core_steps/transformations/test_byte_track.py
Labels: release 0.19.0

#651 Add line counter visualization block
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/visualizations/line_zone/__init__.py
  inference/core/workflows/core_steps/visualizations/line_zone/v1.py
  tests/workflows/unit_tests/core_steps/visualizations/test_line_counter_zone.py
Labels: release 0.19.0

#644 Describe workflow intefrace
  .github/workflows/integration_tests_inference_server_x86.yml
  .github/workflows/test_package_install_inference_gpu_with_extras.yml
  .github/workflows/test_package_install_inference_with_extras.yml
  inference/core/entities/requests/workflows.py
  inference/core/entities/responses/workflows.py
  inference/core/interfaces/http/handlers/workflows.py
  inference/core/interfaces/http/http_api.py
  inference/core/version.py
  inference/core/workflows/core_steps/analytics/line_counter/v1.py
  inference/core/workflows/core_steps/visualizations/line_zone/v1.py
  inference/core/workflows/execution_engine/core.py
  inference/core/workflows/execution_engine/entities/types.py
  inference/core/workflows/execution_engine/v1/introspection/__init__.py
  inference/core/workflows/execution_engine/v1/introspection/inputs_discovery.py
  inference/core/workflows/execution_engine/v1/introspection/kinds_schemas.py
  inference/core/workflows/execution_engine/v1/introspection/kinds_schemas_register.py
  inference/core/workflows/execution_engine/v1/introspection/outputs_discovery.py
  inference/core/workflows/execution_engine/v1/introspection/types_discovery.py
  tests/inference/integration_tests/test_workflow_endpoints.py
  tests/workflows/unit_tests/core_steps/analytics/test_time_in_zone.py
  tests/workflows/unit_tests/core_steps/transformations/test_byte_track.py
  tests/workflows/unit_tests/core_steps/visualizations/test_line_counter_zone.py
  tests/workflows/unit_tests/core_steps/visualizations/test_polygon_zone.py
  tests/workflows/unit_tests/execution_engine/introspection/test_describe_outputs.py
  tests/workflows/unit_tests/execution_engine/introspection/test_inputs_discovery.py
  tests/workflows/unit_tests/execution_engine/introspection/test_types_discovery.py
  tests/workflows/unit_tests/execution_engine/test_core.py
Labels: release-branch, release 0.19.0

#655 Return top prediction by confidence
  inference/core/workflows/core_steps/common/query_language/entities/enums.py
  inference/core/workflows/core_steps/common/query_language/operations/detections/base.py
  tests/workflows/integration_tests/execution/test_workflow_top_prediction.py
Labels: release 0.20.0

#662 Switch base class of blur and pixelate to PredictionsVisualizationManifest / PredictionsVisualizationBlock
  inference/core/workflows/core_steps/visualizations/blur/v1.py
  inference/core/workflows/core_steps/visualizations/pixelate/v1.py
Labels: release 0.20.0

#663 Fix docs links
  docs/enterprise/active-learning/active_learning.md
  docs/enterprise/active-learning/classes_based.md
  docs/enterprise/active-learning/close_to_threshold_sampling.md
  docs/enterprise/active-learning/detection_number.md
  docs/enterprise/active-learning/random_sampling.md
  docs/foundation/clip.md
  docs/index.md
  docs/inference_helpers/inference_sdk.md
  docs/models/from_local_weights.md
  docs/server_configuration/environmental_variables.md
  docs/using_inference/inference_pipeline.md
  docs/using_inference/native_python_api.md
  docs/workflows/create_workflow_block.md
  docs/workflows/custom_python_code_blocks.md
  docs/workflows/workflows_execution_engine.md
  inference/core/interfaces/stream/inference_pipeline.py
  tests/workflows/unit_tests/core_steps/classical_cv/test_sift_comparison_v2.py
Labels: release 0.20.0

#656 Add Rename Classes UQL Operation
  inference/core/workflows/core_steps/common/query_language/entities/operations.py
  inference/core/workflows/core_steps/common/query_language/operations/core.py
  inference/core/workflows/core_steps/common/query_language/operations/detections/base.py
  tests/workflows/integration_tests/execution/assets/image_credits.txt
  tests/workflows/integration_tests/execution/assets/multi-fruit.jpg
  tests/workflows/integration_tests/execution/conftest.py
  tests/workflows/integration_tests/execution/test_workflow_with_detection_renaming.py
  tests/workflows/unit_tests/core_steps/common/query_language/operations/detections/__init__.py
  tests/workflows/unit_tests/core_steps/common/query_language/operations/detections/test_base.py
Labels: release 0.20.0

#654 Added the Ability to Use Rectilinear Polygons in the Dynamic Zone Block
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/transformations/bounding_rect/__init__.py
  inference/core/workflows/core_steps/transformations/bounding_rect/v1.py
  tests/workflows/integration_tests/execution/test_workflow_with_bounding_rectangle.py
  tests/workflows/unit_tests/core_steps/transformations/test_bounding_rect.py
Labels: release 0.20.0

#661 Florence2 workflows block
  .github/workflows/integration_tests_workflows_x86.yml
  docker/dockerfiles/Dockerfile.onnx.gpu.dev
  docs/workflows/blocks.md
  docs/workflows/gallery_index.md
  docs/workflows/kinds.md
  inference/core/entities/responses/inference.py
  inference/core/version.py
  inference/core/workflows/core_steps/formatters/vlm_as_detector/v1.py
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/models/foundation/anthropic_claude/v1.py
  inference/core/workflows/core_steps/models/foundation/florence2/__init__.py
  inference/core/workflows/core_steps/models/foundation/florence2/v1.py
  inference/core/workflows/core_steps/models/foundation/google_gemini/v1.py
  inference/models/florence2/florence2.py
  inference/models/transformers/transformers.py
  tests/inference/models_predictions_tests/test_florence2.py
  tests/workflows/integration_tests/execution/conftest.py
  tests/workflows/integration_tests/execution/test_workflow_with_bounding_rectangle.py
  tests/workflows/integration_tests/execution/test_workflow_with_florence2.py
  tests/workflows/unit_tests/core_steps/formatters/test_vlm_as_detector.py
  tests/workflows/unit_tests/core_steps/models/foundation/test_florence2.py
  tests/workflows/unit_tests/core_steps/transformations/test_bounding_rect.py
Labels: release-branch, release 0.20.0

#670 Line counter improvements
  inference/core/version.py
  inference/core/workflows/core_steps/analytics/line_counter/v1.py
  inference/core/workflows/core_steps/visualizations/line_zone/v1.py
  tests/workflows/unit_tests/core_steps/visualizations/test_line_counter_zone.py
Labels: release-branch, release 0.20.1

#646 `gstreamer` backend in `inference`
  development/stream_interface/create_dummy_streams.py
  development/stream_interface/inference_pipeline_demo.py
  development/stream_interface/stream_video.py
  docker/dockerfiles/Dockerfile.onnx.cpu
  docker/dockerfiles/Dockerfile.onnx.cpu.parallel
  docker/dockerfiles/Dockerfile.onnx.cpu.slim
  docker/dockerfiles/Dockerfile.onnx.cpu.stream_manager
  docker/dockerfiles/Dockerfile.onnx.gpu
  docker/dockerfiles/Dockerfile.onnx.gpu.parallel
  docker/dockerfiles/Dockerfile.onnx.gpu.slim
  docker/dockerfiles/Dockerfile.onnx.gpu.stream_manager
  docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
  docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1.stream_manager
  docker/dockerfiles/Dockerfile.onnx.lambda
  docker/dockerfiles/Dockerfile.onnx.lambda.slim
  docker/dockerfiles/Dockerfile.onnx.trt
  docker/dockerfiles/Dockerfile.onnx.udp.gpu
  docker/dockerfiles/Dockerfile.stream_management_api
Labels: release 0.21.0

#677 Add workflow schema api docs
  docs/notebooks/inference_pipeline_rtsp.ipynb
  docs/notebooks/rgb_anomaly_detection.ipynb
  docs/notebooks/workflow_schema_api.ipynb
  docs/workflows/schema_api.md
  mkdocs.yml
Labels: release 0.21.0

#676 Fix lora
  inference/models/transformers/transformers.py
Labels: release 0.21.0

#674 Add ability to parametrise class remap UQL operation
  inference/core/workflows/core_steps/common/query_language/entities/operations.py
  inference/core/workflows/core_steps/common/query_language/operations/detections/base.py
  tests/workflows/integration_tests/execution/test_workflow_with_detection_renaming.py
  tests/workflows/unit_tests/core_steps/common/query_language/operations/detections/test_base.py
Labels: release 0.21.0

#678 Add `transformers` extra to dev setup py
  .github/workflows/integration_tests_inference_server_x86.yml
  setup.py
Labels: release 0.21.0

#680 Fix license link in docs
  docs/fine-tuned/yolonas.md
  docs/fine-tuned/yolov10.md
  docs/fine-tuned/yolov5.md
  docs/fine-tuned/yolov7.md
  docs/fine-tuned/yolov8.md
  docs/fine-tuned/yolov9.md
  docs/index.md
  docs/quickstart/licensing.md
Labels: release 0.21.0

#681 Add Stability AI inpainting
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/models/foundation/stability_ai/__init__.py
  inference/core/workflows/core_steps/models/foundation/stability_ai/inpainting/__init__.py
  inference/core/workflows/core_steps/models/foundation/stability_ai/inpainting/v1.py
Labels: release 0.21.0

#683 Image preprocessing block (flip, rotate, resize)
  inference/core/workflows/core_steps/classical_cv/image_preprocessing/__init__.py
  inference/core/workflows/core_steps/classical_cv/image_preprocessing/v1.py
  inference/core/workflows/core_steps/loader.py
  tests/workflows/integration_tests/execution/test_workflow_with_image_preprocessing.py
Labels: release 0.21.0

#675 Add metadata for VLM blocks
  docs/workflows/kinds.md
  inference/core/workflows/core_steps/common/vlms.py
  inference/core/workflows/core_steps/models/foundation/anthropic_claude/v1.py
  inference/core/workflows/core_steps/models/foundation/florence2/v1.py
  inference/core/workflows/core_steps/models/foundation/google_gemini/v1.py
  inference/core/workflows/core_steps/models/foundation/openai/v2.py
Labels: release 0.21.0

#672 Masked crop block
  inference/core/workflows/core_steps/transformations/dynamic_crop/v1.py
  tests/workflows/integration_tests/execution/test_workflow_with_masked_crop.py
  tests/workflows/unit_tests/core_steps/transformations/test_crop.py
Labels: release 0.21.0

#682 Add a path deviation analytics block to workflows
  development/stream_interface/path_deviation_demo.py
  inference/core/workflows/core_steps/analytics/path_deviation/__init__.py
  inference/core/workflows/core_steps/analytics/path_deviation/v1.py
  inference/core/workflows/core_steps/analytics/time_in_zone/v1.py
  inference/core/workflows/core_steps/common/serializers.py
  inference/core/workflows/core_steps/transformations/bounding_rect/v1.py
  inference/core/workflows/execution_engine/constants.py
  tests/workflows/unit_tests/core_steps/analytics/test_path_deviation.py
Labels: release 0.21.0

#679 Video processing in `inference` server
  development/stream_interface/workflows_demo.py
  docker/config/cpu_http.py
  docker/config/gpu_http.py
  docker/dockerfiles/Dockerfile.onnx.cpu
  docker/dockerfiles/Dockerfile.onnx.gpu
  docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
  docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
  docs/workflows/video_processing/overview.md
  inference/core/env.py
  inference/core/interfaces/camera/video_source.py
  inference/core/interfaces/http/http_api.py
  inference/core/interfaces/stream/inference_pipeline.py
  inference/core/interfaces/stream/model_handlers/workflows.py
  inference/core/interfaces/stream/sinks.py
  inference/core/interfaces/stream_manager/__init__.py
  inference/core/interfaces/stream_manager/api/__init__.py
  inference/core/interfaces/stream_manager/api/entities.py
  inference/core/interfaces/stream_manager/api/errors.py
  inference/core/interfaces/stream_manager/api/stream_manager_client.py
  inference/core/interfaces/stream_manager/manager_app/__init__.py
  inference/core/interfaces/stream_manager/manager_app/app.py
  inference/core/interfaces/stream_manager/manager_app/communication.py
  inference/core/interfaces/stream_manager/manager_app/entities.py
  inference/core/interfaces/stream_manager/manager_app/errors.py
  inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py
  inference/core/interfaces/stream_manager/manager_app/serialisation.py
  inference/core/interfaces/stream_manager/manager_app/tcp_server.py
  inference/core/version.py
  inference_cli/lib/container_adapter.py
  inference_cli/server.py
  inference_sdk/http/client.py
  inference_sdk/utils/decorators.py
  mkdocs.yml
  tests/inference/integration_tests/test_video_processing_endpoints.py
  tests/inference/unit_tests/core/interfaces/stream/test_sinks.py
  tests/inference/unit_tests/core/interfaces/stream_manager/__init__.py
  tests/inference/unit_tests/core/interfaces/stream_manager/api/__init__.py
  tests/inference/unit_tests/core/interfaces/stream_manager/api/test_stream_manager_client.py
  tests/inference/unit_tests/core/interfaces/stream_manager/manager_app/__init__.py
  tests/inference/unit_tests/core/interfaces/stream_manager/manager_app/test_communucation.py
  tests/inference/unit_tests/core/interfaces/stream_manager/manager_app/test_inference_pipeline_manager.py
  tests/inference/unit_tests/core/interfaces/stream_manager/manager_app/test_serialisation.py
  tests/inference/unit_tests/core/interfaces/stream_manager/manager_app/test_tcp_server.py
  tests/inference/unit_tests/enterprise/stream_management/manager/test_app.py
  tests/inference_sdk/unit_tests/http/test_client.py
  tests/workflows/unit_tests/core_steps/analytics/test_path_deviation.py
Labels: release-branch, release 0.21.0

#689 Add path deviation block
  inference/core/workflows/core_steps/loader.py
Labels: release 0.21.0
