Repository roboflow/inference, pull requests merged in 2024-11, with the labels that each got.

#774 Pass countinference to usage collector
  inference/core/interfaces/http/http_api.py
  inference/usage_tracking/collector.py
Labels: release 0.26.0

#767 Do not run tests if branch is not up to date with main
  .github/workflows/integration_tests_inference_cli_x86.yml
  .github/workflows/integration_tests_inference_models.yml
  .github/workflows/integration_tests_workflows_x86.yml
  .github/workflows/is_mergeable.yml
  .github/workflows/static_code_analysis.yml
  .github/workflows/test_package_install_inference.yml
  .github/workflows/test_package_install_inference_cli.yml
  .github/workflows/test_package_install_inference_gpu.yml
  .github/workflows/test_package_install_inference_gpu_with_extras.yml
  .github/workflows/test_package_install_inference_sdk.yml
  .github/workflows/test_package_install_inference_with_extras.yml
  .github/workflows/unit_tests_inference_cli_x86.yml
  .github/workflows/unit_tests_inference_sdk_x86.yml
  .github/workflows/unit_tests_inference_x86.yml
  .github/workflows/unit_tests_workflows_x86.yml
Labels: release 0.26.0

#777 Fixing the bug with two stage workflow and continue-if failing when nothing gets detected by primary model
  inference/core/workflows/execution_engine/v1/executor/execution_data_manager/step_input_assembler.py
  tests/workflows/integration_tests/execution/test_workflow_with_two_stage_models_and_flow_control.py
  tests/workflows/unit_tests/core_steps/visualizations/test_keypoints.py
Labels: release 0.26.0

#778 Add hostname with optional DEDICATED_DEPLOYMENT_ID to usage payload
  inference/core/env.py
  inference/core/version.py
  inference/usage_tracking/collector.py
  tests/inference/unit_tests/usage_tracking/test_collector.py
Labels: release 0.26.0

#780 Remove debug step from 'Test package install - inference-gpu'
  .github/workflows/test_package_install_inference_gpu.yml
Labels: release 0.26.0

#779 Subsampling video frame rate
  development/workflows_examples/video_analysis/aggregating_objects_passing_data.py
  docs/using_inference/inference_pipeline.md
  inference/core/env.py
  inference/core/interfaces/camera/video_source.py
  inference/core/interfaces/stream/inference_pipeline.py
  inference/core/interfaces/stream/utils.py
  tests/inference/unit_tests/core/interfaces/camera/test_video_source.py
Labels: release 0.26.0

#781 Return single top class confidence for mulit-label predictions
  inference/core/workflows/core_steps/common/query_language/entities/enums.py
  inference/core/workflows/core_steps/common/query_language/operations/classification_results/base.py
  tests/workflows/unit_tests/core_steps/common/query_language/operations/test_classification_results_operations.py
Labels: release 0.26.0

#762 Add Jetpack 6 Support
  .github/workflows/docker.jetson.6.0.0.yml
  .github/workflows/test.jetson_6.0.0.yml
  docker/dockerfiles/Dockerfile.onnx.jetson.6.0.0
  docker/dockerfiles/README.md
  docs/models.md
  docs/quickstart/devices.md
  docs/quickstart/docker.md
  examples/inference-client/README.md
  inference_cli/lib/container_adapter.py
  requirements/requirements.jetson.txt
Labels: release 0.26.0

#783 Add gzip support
  inference/core/interfaces/http/http_api.py
  inference/core/interfaces/http/middlewares/__init__.py
  inference/core/interfaces/http/middlewares/gzip.py
Labels: release 0.26.0

#782 avoiding downloading images if possible
  development/benchmark_scripts/benchmark_owlv2_inference_time.py
  inference/models/owlv2/owlv2.py
  tests/inference/models_predictions_tests/test_owlv2.py
Labels: release 0.26.0

#794 Florence finetunes in workflows
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/models/foundation/florence2/v1.py
  inference/core/workflows/core_steps/models/foundation/florence2/v2.py
  inference/models/transformers/transformers.py
Labels: release 0.27.0

#802 Remove reset from YOLO settings
  inference/models/yolo_world/yolo_world.py
Labels: release 0.27.0

#807 Fix builds broken by #803
  docker/dockerfiles/Dockerfile.onnx.cpu
  docker/dockerfiles/Dockerfile.onnx.cpu.dev
  docker/dockerfiles/Dockerfile.onnx.cpu.parallel
  docker/dockerfiles/Dockerfile.onnx.cpu.slim
  docker/dockerfiles/Dockerfile.onnx.cpu.stream_manager
  docker/dockerfiles/Dockerfile.onnx.gpu
  docker/dockerfiles/Dockerfile.onnx.gpu.dev
  docker/dockerfiles/Dockerfile.onnx.gpu.parallel
  docker/dockerfiles/Dockerfile.onnx.gpu.slim
  docker/dockerfiles/Dockerfile.onnx.gpu.stream_manager
  docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
  docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1.stream_manager
  docker/dockerfiles/Dockerfile.onnx.jetson.6.0.0
  docker/dockerfiles/Dockerfile.onnx.lambda
  docker/dockerfiles/Dockerfile.onnx.lambda.slim
  docker/dockerfiles/Dockerfile.onnx.trt
  docker/dockerfiles/Dockerfile.onnx.udp.gpu
  docker/dockerfiles/Dockerfile.stream_management_api
  requirements/requirements.waf.txt
Labels: release 0.27.0

#810 Attempt to fix builds
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1.stream_manager
  requirements/_requirements.txt
  requirements/requirements.cli.txt
  requirements/requirements.hosted.txt
  requirements/requirements.jetson.txt
  requirements/requirements.parallel.txt
  requirements/requirements.sdk.http.txt
Labels: release 0.27.0

#798 Adjust Roboflow models to primarily use `base64` payloads
  inference/core/workflows/core_steps/models/foundation/clip_comparison/v2.py
  inference/core/workflows/core_steps/models/foundation/ocr/v1.py
  inference/core/workflows/core_steps/models/foundation/yolo_world/v1.py
  inference/core/workflows/core_steps/models/roboflow/instance_segmentation/v1.py
  inference/core/workflows/core_steps/models/roboflow/keypoint_detection/v1.py
  inference/core/workflows/core_steps/models/roboflow/multi_class_classification/v1.py
  inference/core/workflows/core_steps/models/roboflow/multi_label_classification/v1.py
  inference/core/workflows/core_steps/models/roboflow/object_detection/v1.py
  inference/core/workflows/execution_engine/entities/base.py
Labels: release 0.27.0

#812 Fix SAM2 dependencies
  requirements/_requirements.txt
Labels: release 0.27.0

#811 Fix issue with label visualisation
  inference/core/workflows/core_steps/visualizations/label/v1.py
  tests/workflows/integration_tests/execution/test_workflow_with_label_visualization.py
Labels: release 0.27.0

#813 bumping owlv2 version and putting cache size in env
  inference/core/env.py
  inference/models/owlv2/owlv2.py
Labels: release 0.27.0

#809 Image classification viz
  inference/core/version.py
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/visualizations/classification_label/__init__.py
  inference/core/workflows/core_steps/visualizations/classification_label/v1.py
  tests/workflows/integration_tests/execution/test_workflow_with_classification_multi-label_visualization.py
  tests/workflows/integration_tests/execution/test_workflow_with_classification_single-label_visualization.py
  tests/workflows/unit_tests/core_steps/visualizations/test_classification_label.py
Labels: release 0.27.0

#814 Fix label visualization once again
  inference/core/workflows/core_steps/visualizations/label/v1.py
  tests/workflows/integration_tests/execution/test_workflow_with_label_visualization.py
Labels: release 0.27.0

#823 Fix issue with Workflows blocks for Roboflow models v2 not using base64
  inference/core/workflows/core_steps/models/roboflow/instance_segmentation/v1.py
  inference/core/workflows/core_steps/models/roboflow/instance_segmentation/v2.py
  inference/core/workflows/core_steps/models/roboflow/keypoint_detection/v1.py
  inference/core/workflows/core_steps/models/roboflow/keypoint_detection/v2.py
  inference/core/workflows/core_steps/models/roboflow/multi_class_classification/v2.py
  inference/core/workflows/core_steps/models/roboflow/multi_label_classification/v2.py
  inference/core/workflows/core_steps/models/roboflow/object_detection/v1.py
  inference/core/workflows/core_steps/models/roboflow/object_detection/v2.py
  tests/inference/hosted_platform_tests/conftest.py
  tests/inference/hosted_platform_tests/workflows_examples/conftest.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/__init__.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/__init__.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_classification.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_instance_segmentation.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_keypoints_detection.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v1/test_workflow_for_object_detection.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/__init__.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_classification.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_instance_segmentation.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_keypoints_detection.py
  tests/inference/hosted_platform_tests/workflows_examples/roboflow_models/v2/test_workflow_for_object_detection.py
  tests/workflows/integration_tests/execution/assets/asl_image.jpg
  tests/workflows/integration_tests/execution/assets/image_credits.txt
Labels: release 0.28.0

#825 Fix bug with primitive types parsing in Worklfows
  docs/workflows/blocks.md
  docs/workflows/kinds.md
  inference/core/workflows/execution_engine/introspection/schema_parser.py
Labels: release 0.28.0

#827 Always include internal envs if set
  inference/usage_tracking/collector.py
Labels: release 0.28.0

#818 Model Monitoring Inference Aggregator block
  inference/core/roboflow_api.py
  inference/core/version.py
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/sinks/roboflow/model_monitoring_inference_aggregator/v1.py
  tests/workflows/unit_tests/core_steps/sinks/roboflow/test_model_monitoring_inference_aggregator.py
Labels: release 0.28.0

#836 Fix: CUDA context was failing to load in child-process
  docker/config/cpu_http.py
  docker/config/gpu_http.py
  docker/dockerfiles/Dockerfile.onnx.gpu
  docker/dockerfiles/Dockerfile.onnx.gpu.dev
  docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
  docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
  docker/dockerfiles/Dockerfile.onnx.jetson.6.0.0
  docs/server_configuration/environmental_variables.md
  inference/core/env.py
  inference/core/interfaces/stream_manager/manager_app/app.py
  inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py
Labels: release 0.29.0

#840 Update Docker Tag Logic
  .github/actions/determine-tags/action.yml
  .github/workflows/docker.cpu.yml
  .github/workflows/docker.gpu.yml
Labels: release 0.29.0

#843 Don't Require API Keys for Public Workflows
  inference/core/entities/requests/workflows.py
  inference/core/roboflow_api.py
Labels: release 0.29.0

#847 Add workflow to check mergeable state executed on pull request
  .github/workflows/check_if_branch_is_mergeable.yml
Labels: release 0.29.0

#845 Add Slack and Twilio notifiers
  docker/dockerfiles/Dockerfile.onnx.lambda
  docker/dockerfiles/Dockerfile.onnx.lambda.slim
  docs/workflows/blocks.md
  docs/workflows/execution_engine_changelog.md
  docs/workflows/gallery_index.md
  docs/workflows/kinds.md
  inference/core/entities/common.py
  inference/core/env.py
  inference/core/version.py
  inference/core/workflows/core_steps/classical_cv/image_preprocessing/v1.py
  inference/core/workflows/core_steps/common/serializers.py
  inference/core/workflows/core_steps/flow_control/rate_limiter/v1.py
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/models/foundation/anthropic_claude/v1.py
  inference/core/workflows/core_steps/models/foundation/google_gemini/v1.py
  inference/core/workflows/core_steps/models/foundation/google_vision_ocr/v1.py
  inference/core/workflows/core_steps/models/foundation/lmm/v1.py
  inference/core/workflows/core_steps/models/foundation/lmm_classifier/v1.py
  inference/core/workflows/core_steps/models/foundation/openai/v1.py
  inference/core/workflows/core_steps/models/foundation/openai/v2.py
  inference/core/workflows/core_steps/models/foundation/stability_ai/inpainting/v1.py
  inference/core/workflows/core_steps/secrets_providers/__init__.py
  inference/core/workflows/core_steps/secrets_providers/environment_secrets_store/__init__.py
  inference/core/workflows/core_steps/secrets_providers/environment_secrets_store/v1.py
  inference/core/workflows/core_steps/sinks/email_notification/v1.py
  inference/core/workflows/core_steps/sinks/slack/__init__.py
  inference/core/workflows/core_steps/sinks/slack/notification/__init__.py
  inference/core/workflows/core_steps/sinks/slack/notification/v1.py
  inference/core/workflows/core_steps/sinks/twilio/__init__.py
  inference/core/workflows/core_steps/sinks/twilio/sms/__init__.py
  inference/core/workflows/core_steps/sinks/twilio/sms/v1.py
  inference/core/workflows/core_steps/sinks/webhook/v1.py
  inference/core/workflows/execution_engine/entities/types.py
  inference/core/workflows/execution_engine/v1/core.py
  inference/core/workflows/execution_engine/v1/executor/core.py
  inference/core/workflows/execution_engine/v1/executor/execution_data_manager/step_input_assembler.py
  inference/core/workflows/execution_engine/v1/executor/output_constructor.py
  inference/enterprise/workflows/enterprise_blocks/sinks/__init__.py
  inference/enterprise/workflows/enterprise_blocks/sinks/opc_writer/v1.py
  requirements/_requirements.txt
  requirements/requirements.test.unit.txt
  tests/inference/hosted_platform_tests/test_workflows.py
  tests/inference/integration_tests/test_workflow_endpoints.py
  tests/workflows/integration_tests/execution/conftest.py
  tests/workflows/integration_tests/execution/stub_plugins/plugin_testing_non_simd_step_with_optional_outputs/__init__.py
  tests/workflows/integration_tests/execution/test_workflow_with_environment_secrets_store.py
  tests/workflows/integration_tests/execution/test_workflow_with_google_vision_ocr.py
  tests/workflows/integration_tests/execution/test_workflow_with_opc_writer.py
  tests/workflows/integration_tests/execution/test_workflow_with_slack_notification.py
  tests/workflows/integration_tests/execution/test_workflow_with_twillio_notification.py
  tests/workflows/unit_tests/core_steps/sinks/test_slack_notification.py
  tests/workflows/unit_tests/core_steps/sinks/test_twilio_sms_notification.py
Labels: release 0.29.0
