Repository roboflow/inference, pull requests merged in 2024-10, with the labels that each got.

#698 Add block for stitching images
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/transformations/stitch_images/__init__.py
  inference/core/workflows/core_steps/transformations/stitch_images/v1.py
  tests/workflows/integration_tests/execution/assets/stitch/v_left.jpeg
  tests/workflows/integration_tests/execution/assets/stitch/v_right.jpeg
  tests/workflows/integration_tests/execution/conftest.py
  tests/workflows/integration_tests/execution/test_workflow_with_stitch_image.py
  tests/workflows/unit_tests/core_steps/transformations/test_stitch.py
Labels: release 0.22.0

#701 Yolov11
  inference/models/__init__.py
  inference/models/utils.py
  inference/models/yolov11/__init__.py
  inference/models/yolov11/yolov11_instance_segmentation.py
  inference/models/yolov11/yolov11_keypoints_detection.py
  inference/models/yolov11/yolov11_object_detection.py
Labels: release 0.22.0

#709 Add Google Vision OCR block to workflows
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/models/foundation/google_vision_ocr/__init__.py
  inference/core/workflows/core_steps/models/foundation/google_vision_ocr/v1.py
Labels: release 0.22.0

#711 Add port forward to Notebook Landing Page message
  inference/landing/out/_next/static/chunks/app/notebook-instructions/page-f70cded9b659ad6b.js
  inference/landing/out/notebook-instructions.html
  inference/landing/src/app/notebook-instructions/page.tsx
Labels: release 0.22.0

#702 Add optional descriptions to dynamic blocks
  inference/core/workflows/execution_engine/introspection/blocks_loader.py
  inference/core/workflows/execution_engine/v1/dynamic_blocks/block_assembler.py
  inference/core/workflows/execution_engine/v1/dynamic_blocks/entities.py
Labels: release 0.22.0

#704 Add descriptions to task types in `VLM as Detector`
  inference/core/workflows/core_steps/formatters/vlm_as_detector/v1.py
Labels: release 0.22.0

#713 Added the Size Measurement Block
  inference/core/workflows/core_steps/classical_cv/size_measurement/__init__.py
  inference/core/workflows/core_steps/classical_cv/size_measurement/v1.py
  inference/core/workflows/core_steps/loader.py
  inference/models/__init__.py
  inference/models/yolov11/__init__.py
  tests/workflows/unit_tests/core_steps/classical_cv/test_size_measurement.py
Labels: release 0.22.0

#712 Fix prometheus scraping
  docker/config/cpu_http.py
  docker/config/gpu_http.py
  docker/dockerfiles/Dockerfile.onnx.cpu
  docker/dockerfiles/Dockerfile.onnx.cpu.dev
  docker/dockerfiles/Dockerfile.onnx.cpu.parallel
  docker/dockerfiles/Dockerfile.onnx.cpu.slim
  docker/dockerfiles/Dockerfile.onnx.gpu
  docker/dockerfiles/Dockerfile.onnx.gpu.dev
  docker/dockerfiles/Dockerfile.onnx.gpu.parallel
  docker/dockerfiles/Dockerfile.onnx.gpu.slim
  docker/dockerfiles/Dockerfile.onnx.jetson.4.5.0
  docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1
  docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1
  docker/dockerfiles/Dockerfile.onnx.trt
  inference/core/env.py
  inference/core/interfaces/http/http_api.py
Labels: release 0.22.0

#715 Add tests for Google Vision OCR
  .github/workflows/hosted_inference_e2e_test_production.yml
  .github/workflows/hosted_inference_e2e_test_staging.yml
  inference/core/workflows/core_steps/models/foundation/google_vision_ocr/v1.py
  tests/inference/hosted_platform_tests/conftest.py
  tests/inference/hosted_platform_tests/workflows_examples/test_workflow_with_google_ocr.py
  tests/workflows/integration_tests/execution/test_workflow_with_detection_plus_ocr.py
  tests/workflows/integration_tests/execution/test_workflow_with_google_vision_ocr.py
  tests/workflows/integration_tests/execution/test_workflow_with_stitch_image.py
  tests/workflows/unit_tests/core_steps/classical_cv/test_size_measurement.py
  tests/workflows/unit_tests/core_steps/control_flow/test_control_flow.py
  tests/workflows/unit_tests/core_steps/transformations/test_stitch.py
Labels: release 0.22.0

#718 Fix the problem with VLMs on batch inference
  inference/core/workflows/core_steps/models/foundation/anthropic_claude/v1.py
  inference/core/workflows/core_steps/models/foundation/google_gemini/v1.py
  inference/core/workflows/core_steps/models/foundation/openai/v2.py
  tests/workflows/integration_tests/execution/test_workflow_with_claude_models.py
  tests/workflows/integration_tests/execution/test_workflow_with_gemini_models.py
  tests/workflows/integration_tests/execution/test_workflow_with_open_ai_models.py
Labels: release 0.22.0

#716 Improvements regarding custom python blocks
  development/docs/build_block_docs.py
  docs/workflows/blocks.md
  docs/workflows/create_workflow_block.md
  docs/workflows/internal_data_types.md
  docs/workflows/kinds.md
  inference/core/workflows/execution_engine/entities/types.py
  inference/core/workflows/execution_engine/v1/core.py
  inference/core/workflows/execution_engine/v1/executor/core.py
  mkdocs.yml
  tests/inference/hosted_platform_tests/test_workflows.py
  tests/inference/integration_tests/test_workflow_endpoints.py
  tests/workflows/integration_tests/execution/stub_plugins/input_free_blocks_plugin/__init__.py
  tests/workflows/integration_tests/execution/test_workflow_with_inputless_step.py
  tests/workflows/unit_tests/execution_engine/test_core.py
Labels: release 0.22.0

#717 Add Prometheus CPU/GPU custom metrics and latency
  inference/core/interfaces/http/http_api.py
  inference/core/managers/metrics.py
Labels: release 0.22.0

#723 Add metadata for new blocks
  docker/dockerfiles/Dockerfile.onnx.lambda
  docker/dockerfiles/Dockerfile.onnx.lambda.slim
  inference/core/env.py
  inference/core/roboflow_api.py
  inference/core/version.py
  inference/core/workflows/core_steps/analytics/path_deviation/v1.py
  inference/core/workflows/core_steps/classical_cv/size_measurement/v1.py
  inference/core/workflows/core_steps/models/foundation/google_vision_ocr/v1.py
  inference/core/workflows/core_steps/models/foundation/stability_ai/inpainting/v1.py
  inference/core/workflows/core_steps/transformations/stitch_images/v1.py
  tests/inference/unit_tests/core/test_roboflow_api.py
Labels: release-branch, release 0.22.0

#719 add webrtc to inference pipeline manager
  inference/core/interfaces/camera/entities.py
  inference/core/interfaces/camera/utils.py
  inference/core/interfaces/camera/video_source.py
  inference/core/interfaces/http/http_api.py
  inference/core/interfaces/stream_manager/api/entities.py
  inference/core/interfaces/stream_manager/api/stream_manager_client.py
  inference/core/interfaces/stream_manager/manager_app/app.py
  inference/core/interfaces/stream_manager/manager_app/entities.py
  inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py
  inference/core/interfaces/stream_manager/manager_app/webrtc.py
  inference/core/utils/async_utils.py
  requirements/_requirements.txt
Labels: release 0.23.0

#729 Caching compilation results
  inference/core/workflows/execution_engine/v1/compiler/cache.py
  inference/core/workflows/execution_engine/v1/compiler/core.py
  inference/core/workflows/execution_engine/v1/compiler/syntactic_parser.py
  inference/core/workflows/execution_engine/v1/dynamic_blocks/block_assembler.py
  tests/workflows/unit_tests/execution_engine/compiler/test_cache.py
Labels: release 0.23.0

#734 Video metadata deprecation
  docs/workflows/execution_engine_changelog.md
  docs/workflows/internal_data_types.md
  docs/workflows/kinds.md
  inference/core/interfaces/stream/model_handlers/workflows.py
  inference/core/workflows/core_steps/analytics/line_counter/v2.py
  inference/core/workflows/core_steps/analytics/path_deviation/v2.py
  inference/core/workflows/core_steps/analytics/time_in_zone/v2.py
  inference/core/workflows/core_steps/classical_cv/camera_focus/v1.py
  inference/core/workflows/core_steps/classical_cv/contours/v1.py
  inference/core/workflows/core_steps/classical_cv/convert_grayscale/v1.py
  inference/core/workflows/core_steps/classical_cv/image_blur/v1.py
  inference/core/workflows/core_steps/classical_cv/image_preprocessing/v1.py
  inference/core/workflows/core_steps/classical_cv/sift/v1.py
  inference/core/workflows/core_steps/classical_cv/sift_comparison/v2.py
  inference/core/workflows/core_steps/classical_cv/threshold/v1.py
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/models/foundation/stability_ai/inpainting/v1.py
  inference/core/workflows/core_steps/transformations/absolute_static_crop/v1.py
  inference/core/workflows/core_steps/transformations/byte_tracker/v2.py
  inference/core/workflows/core_steps/transformations/dynamic_crop/v1.py
  inference/core/workflows/core_steps/transformations/image_slicer/v1.py
  inference/core/workflows/core_steps/transformations/perspective_correction/v1.py
  inference/core/workflows/core_steps/transformations/relative_static_crop/v1.py
  inference/core/workflows/core_steps/transformations/stitch_images/v1.py
  inference/core/workflows/core_steps/visualizations/background_color/v1.py
  inference/core/workflows/core_steps/visualizations/blur/v1.py
  inference/core/workflows/core_steps/visualizations/bounding_box/v1.py
  inference/core/workflows/core_steps/visualizations/circle/v1.py
  inference/core/workflows/core_steps/visualizations/color/v1.py
  inference/core/workflows/core_steps/visualizations/common/base_colorable.py
  inference/core/workflows/core_steps/visualizations/corner/v1.py
  inference/core/workflows/core_steps/visualizations/crop/v1.py
  inference/core/workflows/core_steps/visualizations/dot/v1.py
  inference/core/workflows/core_steps/visualizations/ellipse/v1.py
  inference/core/workflows/core_steps/visualizations/halo/v1.py
  inference/core/workflows/core_steps/visualizations/label/v1.py
  inference/core/workflows/core_steps/visualizations/line_zone/v1.py
  inference/core/workflows/core_steps/visualizations/mask/v1.py
  inference/core/workflows/core_steps/visualizations/pixelate/v1.py
  inference/core/workflows/core_steps/visualizations/polygon/v1.py
  inference/core/workflows/core_steps/visualizations/polygon_zone/v1.py
  inference/core/workflows/core_steps/visualizations/triangle/v1.py
  inference/core/workflows/execution_engine/entities/base.py
  inference/core/workflows/execution_engine/entities/types.py
  inference/core/workflows/execution_engine/v1/core.py
  inference/core/workflows/execution_engine/v1/executor/runtime_input_assembler.py
  mkdocs.yml
  tests/workflows/unit_tests/core_steps/analytics/test_line_counter_v1.py
  tests/workflows/unit_tests/core_steps/analytics/test_line_counter_v2.py
  tests/workflows/unit_tests/core_steps/analytics/test_path_deviation_v1.py
  tests/workflows/unit_tests/core_steps/analytics/test_path_deviation_v2.py
  tests/workflows/unit_tests/core_steps/analytics/test_time_in_zone_v1.py
  tests/workflows/unit_tests/core_steps/analytics/test_time_in_zone_v2.py
  tests/workflows/unit_tests/core_steps/transformations/test_absolute_static_crop.py
  tests/workflows/unit_tests/core_steps/transformations/test_byte_track_v1.py
  tests/workflows/unit_tests/core_steps/transformations/test_byte_track_v2.py
  tests/workflows/unit_tests/core_steps/transformations/test_crop.py
  tests/workflows/unit_tests/core_steps/transformations/test_relative_static_crop.py
  tests/workflows/unit_tests/execution_engine/entities/test_base.py
  tests/workflows/unit_tests/execution_engine/executor/test_runtime_input_assembler.py
Labels: release 0.23.0

#733 Model Comparison Visualization
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/visualizations/common/annotators/halo.py
  inference/core/workflows/core_steps/visualizations/common/annotators/model_comparison.py
  inference/core/workflows/core_steps/visualizations/common/annotators/polygon.py
  inference/core/workflows/core_steps/visualizations/halo/v1.py
  inference/core/workflows/core_steps/visualizations/model_comparison/__init__.py
  inference/core/workflows/core_steps/visualizations/model_comparison/v1.py
  inference/core/workflows/core_steps/visualizations/polygon/v1.py
  tests/workflows/unit_tests/core_steps/visualizations/test_model_comparison.py
Labels: release 0.23.0

#739 Retrieve device stats for docker containers
  docs/server_configuration/environmental_variables.md
  docs/server_configuration/service_telemetry.md
  inference/core/env.py
  inference/core/interfaces/http/http_api.py
  inference/core/managers/metrics.py
  inference/core/utils/container.py
  mkdocs.yml
Labels: release 0.23.0

#731 Add Distance Measurement Block
  inference/core/workflows/core_steps/classical_cv/distance_measurement/__init__.py
  inference/core/workflows/core_steps/classical_cv/distance_measurement/v1.py
  inference/core/workflows/core_steps/loader.py
  tests/workflows/unit_tests/core_steps/classical_cv/test_distance_measurement.py
Labels: release 0.23.0

#743 Fix/byte track 0 fps with webrtc
  inference/core/interfaces/camera/entities.py
  inference/core/interfaces/stream_manager/manager_app/entities.py
  inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py
  inference/core/interfaces/stream_manager/manager_app/webrtc.py
  inference/core/workflows/core_steps/transformations/byte_tracker/v2.py
  tests/workflows/unit_tests/core_steps/transformations/test_byte_track_v2.py
Labels: release 0.23.0

#746 Loose `typer` requirements
  requirements/requirements.cli.txt
Labels: release 0.24.0

#705 Add StabilizeTrackedDetectionsBlock
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/transformations/stabilize_detections/__init__.py
  inference/core/workflows/core_steps/transformations/stabilize_detections/v1.py
  tests/workflows/unit_tests/core_steps/transformations/test_stabilize_detections.py
Labels: release 0.24.0

#751 Speed-up webrtc inference pipeline
  inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py
  inference/core/interfaces/stream_manager/manager_app/webrtc.py
  inference/core/utils/async_utils.py
Labels: release 0.24.0

#750 Adding inference metrics to the prometheus scraper
  inference/core/interfaces/http/http_api.py
  inference/core/managers/prometheus.py
Labels: release 0.24.0

#737 Foundations for video analytics
  development/workflows_examples/__init__.py
  development/workflows_examples/video_analysis/__init__.py
  development/workflows_examples/video_analysis/aggregating_objects_passing_data.py
  development/workflows_examples/video_analysis/using_webhook_sink.py
  development/workflows_examples/video_analysis/webhook_server.py
  docker/dockerfiles/Dockerfile.onnx.lambda
  docker/dockerfiles/Dockerfile.onnx.lambda.slim
  docs/workflows/blocks.md
  docs/workflows/kinds.md
  inference/core/env.py
  inference/core/version.py
  inference/core/workflows/core_steps/analytics/data_aggregator/__init__.py
  inference/core/workflows/core_steps/analytics/data_aggregator/v1.py
  inference/core/workflows/core_steps/common/query_language/entities/operations.py
  inference/core/workflows/core_steps/common/query_language/operations/core.py
  inference/core/workflows/core_steps/common/query_language/operations/detections/base.py
  inference/core/workflows/core_steps/common/query_language/operations/dictionaries/__init__.py
  inference/core/workflows/core_steps/common/query_language/operations/dictionaries/base.py
  inference/core/workflows/core_steps/common/query_language/operations/images/base.py
  inference/core/workflows/core_steps/flow_control/rate_limiter/__init__.py
  inference/core/workflows/core_steps/flow_control/rate_limiter/v1.py
  inference/core/workflows/core_steps/formatters/csv/__init__.py
  inference/core/workflows/core_steps/formatters/csv/v1.py
  inference/core/workflows/core_steps/loader.py
  inference/core/workflows/core_steps/sinks/email_notification/__init__.py
  inference/core/workflows/core_steps/sinks/email_notification/v1.py
  inference/core/workflows/core_steps/sinks/local_file/__init__.py
  inference/core/workflows/core_steps/sinks/local_file/v1.py
  inference/core/workflows/core_steps/sinks/webhook/__init__.py
  inference/core/workflows/core_steps/sinks/webhook/v1.py
  inference/core/workflows/core_steps/transformations/byte_tracker/v3.py
  inference/core/workflows/core_steps/visualizations/reference_path/__init__.py
  inference/core/workflows/core_steps/visualizations/reference_path/v1.py
  inference/core/workflows/core_steps/visualizations/trace/__init__.py
  inference/core/workflows/core_steps/visualizations/trace/v1.py
  inference/core/workflows/execution_engine/entities/types.py
  requirements/_requirements.txt
  tests/workflows/integration_tests/execution/conftest.py
  tests/workflows/integration_tests/execution/test_workflow_with_csv_formatter.py
  tests/workflows/integration_tests/execution/test_workflow_with_data_aggregation.py
  tests/workflows/integration_tests/execution/test_workflow_with_file_sink.py
  tests/workflows/integration_tests/execution/test_workflow_with_rate_limiter.py
  tests/workflows/integration_tests/execution/test_workflow_with_reference_path_visualization.py
  tests/workflows/integration_tests/execution/test_workflow_with_trace_visualization.py
  tests/workflows/unit_tests/conftest.py
  tests/workflows/unit_tests/core_steps/common/query_language/operations/test_detections_operations.py
  tests/workflows/unit_tests/core_steps/common/query_language/operations/test_dictionaries_operations.py
  tests/workflows/unit_tests/core_steps/common/query_language/operations/test_image_operations.py
  tests/workflows/unit_tests/core_steps/control_flow/test_rate_limiter.py
  tests/workflows/unit_tests/core_steps/formatters/test_csv.py
  tests/workflows/unit_tests/core_steps/sinks/test_email.py
  tests/workflows/unit_tests/core_steps/sinks/test_local_file.py
  tests/workflows/unit_tests/core_steps/sinks/test_webhook.py
  tests/workflows/unit_tests/core_steps/transformations/test_byte_track_v3.py
  tests/workflows/unit_tests/execution_engine/introspection/test_blocks_loader.py
Labels: release 0.24.0

#748 consumption timeout for inference pipeline processes
  docker/config/cpu_http.py
  docker/config/gpu_http.py
  inference/core/interfaces/stream_manager/manager_app/app.py
  inference/core/interfaces/stream_manager/manager_app/entities.py
  inference/core/interfaces/stream_manager/manager_app/inference_pipeline_manager.py
  inference/core/interfaces/stream_manager/manager_app/webrtc.py
  inference/core/utils/async_utils.py
Labels: release 0.24.0
