Repository roboflow/inference, pull requests merged in 2025-01, with the labels that each got.

#948 add cli requirements to github workflow for generating docs
  .github/workflows/docs.yml
Labels: release 0.34.0

#938 docstrings for SDK reference docs
  .gitignore
  inference_sdk/__init__.py
  inference_sdk/config.py
  inference_sdk/http/__init__.py
  inference_sdk/http/client.py
  inference_sdk/http/entities.py
  inference_sdk/http/errors.py
  inference_sdk/http/utils/__init__.py
  inference_sdk/http/utils/aliases.py
  inference_sdk/http/utils/encoding.py
  inference_sdk/http/utils/executors.py
  inference_sdk/http/utils/iterables.py
  inference_sdk/http/utils/loaders.py
  inference_sdk/http/utils/post_processing.py
  inference_sdk/http/utils/pre_processing.py
  inference_sdk/http/utils/profilling.py
  inference_sdk/http/utils/request_building.py
  inference_sdk/http/utils/requests.py
  inference_sdk/utils/decorators.py
  inference_sdk/utils/environment.py
  mkdocs.yml
Labels: release 0.34.0

#954 Handle optional workflow_id if passed as part of request to /workflows/run
  inference/core/entities/requests/workflows.py
  inference/core/interfaces/http/http_api.py
Labels: release 0.34.0

#947 remove outdated active learning docs
  docs/enterprise/active-learning/active_learning.md
  docs/enterprise/active-learning/classes_based.md
  docs/enterprise/active-learning/close_to_threshold_sampling.md
  docs/enterprise/active-learning/detection_number.md
  docs/enterprise/active-learning/random_sampling.md
  mkdocs.yml
Labels: release 0.34.0

#936 Docs: /start
  README.md
  docs/images/architecture/appliance.svg
  docs/images/architecture/microservice.svg
  docs/images/architecture/pipeline.svg
  docs/index.md
  docs/inputs/images.md
  docs/inputs/index.md
  docs/inputs/industrial/basler.md
  docs/inputs/industrial/flir.md
  docs/inputs/industrial/index.md
  docs/inputs/industrial/lucid.md
  docs/inputs/rtsp/index.md
  docs/inputs/rtsp/reolink.md
  docs/inputs/rtsp/unifi.md
  docs/inputs/video.md
  docs/inputs/webcam.md
  docs/install/cloud/aws.md
  docs/install/cloud/azure.md
  docs/install/cloud/gcp.md
  docs/install/cloud/index.md
  docs/install/enterprise-considerations.md
  docs/install/index.md
  docs/install/jetson.md
  docs/install/linux.md
  docs/install/mac.md
  docs/install/minimum-requirements.md
  docs/install/other.md
  docs/install/raspberry-pi.md
  docs/install/using-your-new-server.md
  docs/install/windows.md
  docs/managed/dedicated.md
  docs/managed/index.md
  docs/managed/serverless.md
  docs/resources.md
  docs/start/getting-started.md
  docs/start/next.md
  docs/start/overview.md
  docs/styles.css
  docs/understand/alternatives.md
  docs/understand/architecture.md
  docs/understand/features.md
  docs/understand/vocabulary.md
  docs/video-tutorials.md
  inference/enterprise/parallel/README.md
  mkdocs.yml
Labels: documentation

#963 Docs: Fix Typo
  docs/index.md
Labels: documentation

#754 Velocity block (w/ Byte Tracker)
  inference/core/workflows/core_steps/analytics/velocity/__init__.py
  inference/core/workflows/core_steps/analytics/velocity/v1.py
  inference/core/workflows/core_steps/loader.py
  tests/workflows/unit_tests/core_steps/analytics/test_velocity.py
Labels: release 0.35.0
